feat: allows to define a prefix for collections / tables
gravitee-io/gravitee-repository-mongodb pull request #186
Opened 2021-02-18 14:19 UTC by ytvnr

Fixes https://github.com/gravitee-io/issues/issues/4715

2021-03-01 09:29 UTC, phiz71 requested changes

2021-03-01 09:29 UTC, phiz71 commented on src/main/resources/scripts/create-index.js
> +db.getCollection(`${prefix}alter_triggers`).reIndex();
```suggestion
db.getCollection(`${prefix}alert_triggers`).dropIndexes();
db.getCollection(`${prefix}alert_triggers`).createIndex( { "referenceType": 1, "referenceId": 1 } );
db.getCollection(`${prefix}alert_triggers`).reIndex();
```

2021-03-01 09:29 UTC, phiz71 commented on src/main/java/io/gravitee/repository/mongodb/ratelimit/MongoRateLimitRepository.java
> +    @Value("${management.mongodb.prefix:}")
What is the default value in that case: null or empty string ?

2021-03-01 09:53 UTC, phiz71 commented on src/main/java/io/gravitee/repository/mongodb/ratelimit/MongoRateLimitRepository.java
> +    @Value("${management.mongodb.prefix:}")
It is an empty string.

2021-03-08 12:05 UTC, ytvnr commented on src/main/resources/scripts/create-index.js
> +db.getCollection(`${prefix}alter_triggers`).reIndex();
done

2021-03-08 14:03 UTC, phiz71 approved these changes

2021-03-10 08:18 UTC, merged